services: docker

before_install:
  - docker build -t dev ./client
script:
  - docker run -e CI=true dev npm test

after_success:
  - docker build -t $DOCKER_ID/fib-client -f ./client/prod.Dockerfile ./client
  - docker build -t $DOCKER_ID/fib-nginx ./nginx
  - docker build -t $DOCKER_ID/fib-server -f ./server/prod.Dockerfile ./server
  - docker build -t $DOCKER_ID/fib-worker -f ./worker/prod.Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push $DOCKER_ID/fib-client
  - docker push $DOCKER_ID/fib-nginx
  - docker push $DOCKER_ID/fib-server
  - docker push $DOCKER_ID/fib-worker
